api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: 'api courses'
    description: 'formation complete'
    collection:
        pagination:
            enabled: false
            items_per_page: 20
            client_enabled: true

